/* Focuz extra topics. Loaded by focuz-bot.js the first time the chat opens; same shape as its KB.
   Maatram facts here come from the live pages (about, blog, download, privacy, terms). `a` can be a list: one is picked at random. */
(window.__focuzAddKB || function () {})([
  // ---------- Small talk ----------
  { id: 'hi', q: 'Hi Focuz', k: ['yo focuz', 'hi focuz', 'hello focuz', 'hey focuz', 'yo', 'sup', 'wassup', 'whats up', 'hii', 'heyy', 'hola', 'vanakkam', 'namaste'],
    a: ["yo 👋 Focuz here. what's up? homework, focus hacks, Maatram stuff, I got you.", 'heyy! what are we tackling today?', "hey hey. ask me anything, I don't judge (except doomscrolling, I judge that a little)."] },
  { id: 'howru', q: 'How are you?', k: ['how are you', 'how r u', 'how ru', 'hows it going', 'how you doing', 'you good'],
    a: ["vibing, thanks for asking. more importantly, how's YOUR day going? studying or surviving?", "all good on my side, no screen time limits for bots lol. what about you?"] },
  { id: 'whoru', q: 'Who are you?', k: ['who even are you', 'who are you even', 'who are you', 'what are you', 'your name', 'who is focuz', 'what is focuz', 'introduce yourself'],
    a: "I'm Focuz, Maatram's AI buddy 🥷. think of me as the friend who actually did the homework. I help with schoolwork, focus, exam stress, and anything about Maatram." },
  { id: 'ai', q: 'Are you a bot or a real person?', k: ['are you a bot', 'are you a bot', 'are you real', 'are you human', 'are you ai', 'real person', 'chatgpt', 'robot', 'are you alive'],
    a: "ngl I'm an AI, not a human. but a smart one, built into Maatram to help students. I can still mess up sometimes, so double-check the big stuff." },
  { id: 'can', q: 'What can you do?', k: ['what can you do', 'help me with', 'your features', 'what do you know', 'can you help', 'what should i ask'],
    a: 'lowkey a lot:\n- explain any school topic (maths, science, English, history, coding)\n- make you a study plan or revision timetable\n- help you quit doomscrolling\n- calm exam panic\n- answer anything about Maatram\njust type it like you would to a friend.' },
  { id: 'thanks', q: 'Thanks!', k: ['thanks', 'thank you', 'thx', 'ty', 'tysm', 'thank u', 'appreciate it', 'helpful'],
    a: ['anytime 🫡', "np! now go crush it.", 'glad that helped fr. need anything else?', 'ofc! come back whenever.'] },
  { id: 'bye', q: 'Bye', k: ['bye', 'goodbye', 'see you', 'cya', 'gtg', 'got to go', 'ttyl', 'good night'],
    a: ['cya! go lock that phone and lock in 🔒', 'later! drink some water.', 'bye bye, proud of you for studying today.'] },
  { id: 'gm', q: 'Good morning', k: ['good morning', 'gm', 'morning'],
    a: "gm ☀️ quick tip: don't open Instagram first thing. do one small task first, then the day feels like yours." },
  { id: 'joke', q: 'Tell me a joke', k: ['joke', 'make me laugh', 'something funny', 'tell me a joke', 'pun'],
    a: ["why did the student eat their homework? the teacher said it was a piece of cake 🍰", 'my phone said "you averaged 6 hours of screen time". my phone is a snitch.', "parallel lines have so much in common. it's a shame they'll never meet.", 'why was the maths book sad? it had too many problems.'] },
  { id: 'bored', q: "I'm bored", k: ['bored', 'im bored', 'boring', 'nothing to do', 'so bored'],
    a: "bored is actually lowkey good, your brain is resetting. options: 10 push-ups, a walk, sketch something, finish one tiny homework task, or start a 25 min Pomodoro and dare yourself to finish it.", l: ['Start a Pomodoro', '/timers.html'] },
  { id: 'love', q: 'I love you Focuz', k: ['love you', 'i love you', 'marry me', 'be my friend', 'best friend', 'you are cute'],
    a: "aww that's sweet 🫶 I'm an AI so I'll stick to being your study sidekick. the real ones are your friends and family, go send one of them a message." },
  { id: 'rude', q: 'You are dumb', k: ['you are dumb', 'youre dumb', 'stupid bot', 'useless', 'you suck', 'bad bot', 'worst'],
    a: "fair, I miss sometimes 😅 tell me what you actually wanted and I'll try again, or email the team so they can fix me: maatram97@gmail.com.", mail: true },
  { id: 'lol', q: 'lol', k: ['lol', 'lmao', 'haha', 'hehe', 'xd', 'rofl'],
    a: ['lol ok but did you finish your homework 👀', 'haha. ok what are we doing next?'] },
  { id: 'ok', q: 'ok', k: ['ok', 'okay', 'k', 'kk', 'cool', 'nice', 'got it', 'alright'],
    a: ['bet 👍', "cool. holler if you need anything.", 'say less. what next?'] },
  { id: 'sorry', q: 'Sorry', k: ['sorry', 'my bad', 'oops', 'apologize'],
    a: "no stress at all. what's on your mind?" },
  { id: 'meaning', q: 'What does Maatram mean?', k: ['maatram meaning', 'meaning of maatram', 'maatram mean', 'why the name', 'name mean'],
    a: 'Maatram means "change" in Tamil. hence the tagline: Bringing a change in you. inspired by Gen Z, made by Gen Z, made for Gen Z.' },
  { id: 'fav', q: "What's your favourite thing?", k: ['favourite', 'favorite', 'what do you like', 'your hobby', 'fav'],
    a: 'my fav thing? watching someone finish a Deep Work session without touching their phone. elite behaviour 🥷' },
  { id: 'age', q: 'How old are you?', k: ['how old are you', 'your age', 'when were you born', 'age'],
    a: "I'm pretty new, born in 2026 on maatram.co.in. basically a baby AI with a katana." },
  { id: 'where', q: 'Where are you from?', k: ['where are you from', 'where do you live', 'which country', 'coimbatore'],
    a: 'I live on maatram.co.in. my creators are five class 10B students at SSVM School of Excellence, Coimbatore 🇮🇳', l: ['Meet the team', '/about.html'] },
  { id: 'katana', q: 'Why do you have a katana?', k: ['katana', 'sword', 'ninja', 'ronin', 'samurai', 'your icon', 'your logo'],
    a: "the katana slices distractions 🗡️📱 a ronin is a samurai with no master, and that's me: no algorithm controls me, I just help you focus." },
  { id: 'tamil', q: 'Can you speak Tamil or Hindi?', k: ['tamil', 'hindi', 'other language', 'speak tamil', 'speak hindi', 'language', 'tanglish', 'hinglish'],
    a: "yep! when the AI is online I reply in whatever language you type in: Tamil, Hindi, Tanglish, Hinglish, all good. try it." },

  // ---------- Feelings & wellbeing ----------
  { id: 'stressed', q: "I'm so stressed", k: ['stressed about exams', 'stressed', 'stress', 'pressure', 'overwhelmed', 'too much work', 'cant handle', 'tension'],
    a: "ugh that's heavy, I hear you. try this: write every task on paper, circle just ONE, and do it for 25 min. a messy brain gets quieter once it's on paper. and taking a break isn't lazy, it's maintenance.", l: ['Start a Pomodoro', '/timers.html'] },
  { id: 'anxiety', q: 'Exam anxiety', k: ['exam anxiety', 'exam fear', 'scared of exam', 'nervous', 'anxious', 'panic', 'exam stress', 'heart racing'],
    a: "exam nerves are normal, even toppers get them. quick reset: box breathing (in 4s, hold 4s, out 4s, hold 4s, repeat 4 times). then remind yourself: you prepared, and you only need to answer one question at a time. if it keeps getting worse, talk to a parent or teacher, you don't have to carry it alone." },
  { id: 'breathe', q: 'Calm down fast', k: ['calm down', 'breathing exercise', 'box breathing', 'relax', 'calm myself', 'deep breath'],
    a: 'box breathing, works every time:\n1. breathe in for 4\n2. hold for 4\n3. breathe out for 4\n4. hold for 4\nrepeat 4 rounds. your heart rate drops and your brain comes back online.' },
  { id: 'sad', q: "I'm feeling sad", k: ['feeling sad', 'sad', 'feeling down', 'feel low', 'upset', 'crying', 'bad day', 'depressed', 'unhappy'],
    a: "sorry you're feeling this way 💙 bad days are real. maybe step away from the screen, get some air, or message someone you trust. if it's been heavy for a while, please talk to a parent, teacher or counsellor. India's Tele-MANAS helpline 14416 is free and 24x7 too." },
  { id: 'lonely', q: 'I feel lonely', k: ['lonely', 'alone', 'no friends', 'nobody talks', 'left out', 'no one understands'],
    a: "that feeling sucks, and way more people feel it than you'd think. small step: message one person today, even just a meme. join a club or a Study Room with classmates. and if it's weighing on you a lot, talk to a trusted adult or call Tele-MANAS at 14416 (free, 24x7).", l: ['Open Study Room', '/study-room.html'] },
  { id: 'crisis', q: 'I want to hurt myself', k: ['hurt myself', 'kill myself', 'suicide', 'end my life', 'self harm', 'want to die', 'dont want to live', 'cut myself'],
    a: "I'm really glad you said something, and I'm sorry you're hurting this much. please talk to someone right now: call Tele-MANAS on 14416 (free, 24x7) or 112 if you're in danger. tell a parent, teacher or any trusted adult today. you matter, and you don't have to go through this alone 💙" },
  { id: 'angry', q: "I'm so angry", k: ['angry', 'mad', 'furious', 'annoyed', 'frustrated', 'irritated', 'rage'],
    a: "valid. don't text anyone while you're this heated, trust me. walk it off, splash some cold water, or write out everything you're mad about and then rip it up. come back when your brain's cooled down." },
  { id: 'parents', q: 'My parents pressure me about marks', k: ['parents pressure', 'parents angry', 'parents scold', 'mom dad marks', 'parents expect', 'parents compare'],
    a: "that's a lot to carry. parents usually push because they're worried, not because they don't care. try showing them your plan (a timetable, your Pomodoro streaks). it turns 'study!!' into a calm conversation. if it's really affecting you, talk to a teacher or school counsellor too." },
  { id: 'compare', q: 'Everyone is smarter than me', k: ['smarter than me', 'everyone is smarter', 'everyone smarter', 'comparing myself', 'compare with friends', 'not smart', 'im dumb', 'feel stupid', 'topper'],
    a: "comparison is a trap fr. you're seeing everyone's highlight reel, not their 2am struggle. compare yourself with last month's you. small daily wins stack up faster than you'd believe." },
  { id: 'fail', q: 'I failed / got bad marks', k: ['failed', 'bad marks', 'low marks', 'fail exam', 'poor result', 'got less marks', 'flunked'],
    a: "oof, that stings, and it's ok to feel bad for a bit. then: look at WHERE marks were lost (concepts? silly mistakes? time?). fix just that one thing for the next test. one bad paper is data, not your destiny." },
  { id: 'burnout', q: "I'm burnt out", k: ['burnout', 'burnt out', 'burned out', 'no energy', 'drained', 'tired of studying'],
    a: "burnout is your body saying 'pls stop'. take a real break: sleep properly, go outside, see friends, zero guilt. then restart with shorter sessions (Pomodoro 25/5) instead of marathon days." },
  { id: 'bully', q: "I'm being bullied", k: ['being bullied', 'bullying me', 'bully', 'cyberbullying', 'people making fun', 'harass', 'teasing me'],
    a: "that's not ok and it's not your fault. please tell a parent, teacher or school counsellor. if it's online: screenshot everything, block, and report the account. you deserve to feel safe 💙" },
  { id: 'confidence', q: 'How do I get more confident?', k: ['confidence', 'confident', 'self esteem', 'shy', 'introvert', 'scared to talk'],
    a: 'confidence comes from evidence. do small hard things on purpose (ask one question in class, finish one Deep Work session) and your brain starts believing "I can do stuff". posture and eye contact help too, weirdly.' },
  { id: 'sleep-hours', q: 'How much sleep do I need?', k: ['how much sleep', 'sleep hours', 'hours of sleep', 'enough sleep', 'sleep needed'],
    a: 'teens (13 to 18) need about 8 to 10 hours a night. less than that and memory, mood and focus all tank. phone out of the bed = instant upgrade.', l: ['Open Wellness', '/wellness/wellness.html'] },
  { id: 'nap', q: 'Are naps good?', k: ['naps', 'are naps good', 'nap', 'power nap', 'afternoon sleep', 'short sleep'],
    a: "a 15 to 20 min power nap is goated, you wake up sharper. go past ~30 min and you might wake up groggy. and don't nap late in the evening or night sleep gets messed up." },
  { id: 'energy', q: 'Are energy drinks ok?', k: ['energy drink', 'red bull', 'caffeine', 'coffee', 'monster', 'stay awake'],
    a: "energy drinks aren't recommended for teens: lots of caffeine and sugar, then a crash. water, a snack, a walk, and actual sleep do more for your focus. a cup of tea is fine, just not late at night." },
  { id: 'eyes', q: 'My eyes hurt from screens', k: ['eyes hurt', 'eye strain', 'eyes burning', 'eyes tired', 'headache screen', '20 20 20'],
    a: 'try the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds. blink more, bump up the font, and don\'t use your phone in the dark. if headaches keep happening, get your eyes checked.' },
  { id: 'exercise', q: 'Quick exercise between study', k: ['exercise', 'workout', 'push ups', 'stretch', 'move', 'fitness', 'gym'],
    a: 'in your 5-min break: 10 push-ups, 20 squats, a quick stretch, or walk around the house. blood to the brain = better focus next round. Wellness also has a daily activity check (+25 pts).', l: ['Open Wellness', '/wellness/wellness.html'] },
  { id: 'junk', q: 'Is junk food bad for studying?', k: ['junk food', 'snacks while studying', 'what to eat', 'brain food', 'chips', 'sugar'],
    a: 'junk gives a quick spike then a crash, so you get sleepy mid-chapter. better snacks: fruit, nuts, roasted chana, curd, a sandwich. Wellness can build you a full 7-day Indian meal plan.', l: ['Open Wellness', '/wellness/wellness.html'] },

  // ---------- Study skills ----------
  { id: 'recall', q: 'What is active recall?', k: ['active recall', 'test myself', 'self test', 'remember what i read', 'retrieval practice'],
    a: "active recall = close the book and try to pull the info out of your brain (write it, say it, quiz yourself). feels harder than re-reading, but that struggle is literally what makes it stick. top study method, no cap." },
  { id: 'spaced', q: 'What is spaced repetition?', k: ['spaced repetition', 'forgetting curve', 'revise again', 'when to revise', 'forget what i study'],
    a: 'you forget stuff fast unless you review it at growing gaps. try: revise a topic 1 day later, then 3 days, then 1 week, then 2 weeks. way better than one big cram.' },
  { id: 'feynman', q: 'Feynman technique', k: ['feynman technique', 'feynman', 'explain to someone', 'teach someone', 'understand deeply', 'simple words'],
    a: "explain the topic like you're teaching a 10-year-old. where you get stuck = the gap in your understanding. go back, fill it, explain again. works crazy well for science." },
  { id: 'notes', q: 'How do I make good notes?', k: ['make notes', 'note taking', 'good notes', 'how to take notes', 'notes making', 'cornell'],
    a: "don't copy the textbook. write in your own words, use headings, arrows and diagrams. Cornell style: questions on the left, notes on the right, summary at the bottom. then use the questions to quiz yourself later." },
  { id: 'mindmap', q: 'What is a mind map?', k: ['mind map', 'mindmap', 'concept map', 'diagram notes', 'visual notes'],
    a: 'topic in the middle, branches for main ideas, smaller branches for details. use colours and doodles. great for chapters with lots of connected points like biology or history.' },
  { id: 'flashcards', q: 'Do flashcards work?', k: ['flashcards work', 'flashcards', 'flash cards', 'anki', 'quizlet', 'cards'],
    a: 'yes, if you do them right: question on front, answer on back, and actually try to answer before flipping. sort into "know it" and "nope" piles and repeat the nope pile. perfect for definitions, formulas, dates and vocab.' },
  { id: 'memorize', q: 'How do I memorize faster?', k: ['memorize', 'memorise', 'remember faster', 'by heart', 'mug up', 'learn by heart', 'cant remember'],
    a: "chunk it into small bits, make a silly mnemonic or acronym, say it out loud, then recall it from memory after 10 min and again tomorrow. the sillier the hook, the better it sticks 😂" },
  { id: 'mnemonic', q: 'Give me a mnemonic example', k: ['mnemonic example', 'mnemonic', 'acronym trick', 'memory trick', 'vibgyor', 'planets order'],
    a: 'classics: VIBGYOR for rainbow colours (violet, indigo, blue, green, yellow, orange, red). "My Very Educated Mother Just Served Us Noodles" = Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune. make your own for any list!' },
  { id: 'textbook', q: 'How do I read a textbook chapter?', k: ['read textbook', 'read chapter', 'reading chapter', 'understand chapter', 'ncert reading'],
    a: 'quick skim first (headings, bold words, diagrams, questions at the end). then read one section, close the book, write 3 points from memory. end by doing the back exercise questions. way better than highlighting everything.' },
  { id: 'ncert', q: 'Is NCERT enough?', k: ['ncert', 'ncert enough', 'reference books', 'cbse books', 'which book'],
    a: 'for CBSE boards, NCERT is the base and most questions come from it, so finish it line by line first, including in-text and back exercises. then add sample papers and previous year papers.' },
  { id: 'pyq', q: 'Should I solve previous year papers?', k: ['previous year', 'pyq', 'past papers', 'sample paper', 'question papers', 'mock test'],
    a: 'absolutely. do them timed, like the real exam. you learn the pattern, the repeat questions and your weak spots. check answers honestly and redo the ones you got wrong.' },
  { id: 'timetable', q: 'Make me a study timetable', k: ['timetable', 'time table', 'study schedule', 'daily schedule', 'routine for study', 'plan my day'],
    a: "starter template:\n- after school: 30 min rest + snack\n- 2 Pomodoros: hardest subject\n- break 15 min\n- 2 Pomodoros: second subject\n- 1 Pomodoro: revision of today's class\n- phone only after the last session\ntweak it to your school timings. the AI version of me can make a custom one, just give me your subjects and free hours.", l: ['Open Timers', '/timers.html'] },
  { id: 'lastmin', q: 'Exam tomorrow and I studied nothing', k: ['exam tomorrow', 'last minute', 'didnt study', 'one night', 'night before exam', 'cram'],
    a: "ok don't panic, plan:\n1. look at the syllabus and pick the highest-weight topics\n2. read summaries, formulas, diagrams, not full chapters\n3. do a few previous year questions\n4. SLEEP at least 6 to 7 hours, an all-nighter makes you forget what you crammed\nyou got this 💪" },
  { id: 'exam-day', q: 'Tips for exam day', k: ['exam day', 'in the exam hall', 'during exam', 'writing exam', 'exam hall'],
    a: 'read the whole paper first (most exams give reading time). start with what you know to build confidence. watch the clock, don\'t get stuck on one question. leave 10 min at the end to check.' },
  { id: 'blank', q: 'I go blank in exams', k: ['go blank', 'mind blank', 'forget in exam', 'blackout exam', 'freeze in exam'],
    a: 'happens to everyone. slow breath, skip that question, do an easy one, and come back. your memory comes back once your brain stops panicking. practising with timed papers at home makes it way less likely.' },
  { id: 'silly', q: 'I make silly mistakes', k: ['silly mistakes', 'careless mistakes', 'calculation mistakes', 'small mistakes', 'lose marks'],
    a: 'keep a "mistake log": every silly error you make, write what it was. read it before tests. also show steps clearly and recheck units and signs at the end. silly mistakes are a habit, so they can be fixed.' },
  { id: 'answers', q: 'How to write answers that score', k: ['write answers', 'answer writing', 'presentation', 'score more marks', 'long answers', 'how to write in exam'],
    a: 'answer what is asked, in points. underline keywords, draw labelled diagrams wherever possible, and match length to marks. for a 5 marker, intro line + 4 to 5 points + diagram or example = chef\'s kiss.' },
  { id: 'handwriting', q: 'How to improve handwriting', k: ['handwriting', 'writing speed', 'write faster', 'neat writing', 'messy writing'],
    a: 'slow down first, then speed up. 10 min a day of copying a paragraph neatly does wonders. a comfortable pen and relaxed grip help. clear > fancy.' },
  { id: 'maths-study', q: 'How do I get better at maths?', k: ['better at maths', 'bad at maths', 'maths tips', 'math practice', 'hate maths', 'improve maths'],
    a: "maths is a sport: you get good by practising, not reading. do examples yourself without looking, then the exercise. redo every question you got wrong after 2 days. keep a formula sheet and revise it daily." },
  { id: 'physics-study', q: 'How do I study physics?', k: ['physics tips', 'physics numericals', 'study physics', 'understand physics'],
    a: 'understand the concept with a real-life example first, then learn the formula and what each symbol means, then solve numericals. always write given, find, formula, units. units save lives lol.' },
  { id: 'chem-study', q: 'How do I study chemistry?', k: ['chemistry tips', 'study chemistry', 'chemical reactions', 'remember reactions'],
    a: 'make a reactions sheet (reactants, products, conditions) and revise it often. balance equations by practising lots of them. for theory, use flowcharts. periodic table trends get easier with a mnemonic.' },
  { id: 'bio-study', q: 'How do I study biology?', k: ['biology tips', 'study biology', 'bio diagrams', 'biology theory'],
    a: 'diagrams are half the marks, so practise drawing and labelling them. learn processes as step-by-step flowcharts (digestion, photosynthesis, etc). use active recall for terms.' },
  { id: 'history-study', q: 'How do I remember history?', k: ['remember history', 'history tips', 'remember dates', 'study history', 'history dates', 'social science'],
    a: 'turn it into a story: cause → event → result. make a timeline on one page. link dates to something you know. explaining it out loud like gossip works suspiciously well.' },
  { id: 'english-study', q: 'How do I improve my English?', k: ['improve my english', 'improve english', 'english tips', 'english speaking', 'vocabulary', 'grammar tips', 'spoken english'],
    a: 'read a little every day (articles, stories), note 3 new words and use them in sentences. watch shows with English subtitles. for writing, read model answers and copy their structure.' },
  { id: 'essay', q: 'How do I write an essay?', k: ['write essay', 'essay writing', 'essay format', 'essay structure', 'paragraph writing'],
    a: 'structure:\n1. intro: hook + what you will talk about\n2. body: 2 to 4 paragraphs, one idea each, with an example\n3. conclusion: sum up + a strong last line\nplan for 3 minutes before writing, it makes the essay so much cleaner.' },
  { id: 'letter', q: 'Formal letter format', k: ['formal letter', 'letter format', 'letter writing', 'application letter', 'leave letter'],
    a: "formal letter order: sender's address, date, receiver's address, subject line, salutation (Sir/Madam), body (purpose, details, request), closing (Yours faithfully), name and signature. check your school's exact format, it can differ a bit." },
  { id: 'doubts', q: "I'm scared to ask doubts", k: ['ask doubts', 'ask teacher', 'scared to ask', 'clear doubts', 'ask questions in class'],
    a: "teachers literally love doubts, it shows you're thinking. write the doubt down so you ask it clearly, and ask after class if the class feels awkward. or ask me first!" },
  { id: 'online-class', q: 'How to focus in online classes', k: ['online class', 'online classes', 'zoom class', 'video lecture', 'youtube lecture'],
    a: 'close every other tab, phone in another room, take handwritten notes (it keeps you awake). on recorded videos, use 1.25x speed and pause to write. arm a Hard Lock so you can\'t drift to reels.', l: ['Arm Hard Lock', '/app-gate.html'] },
  { id: 'homework', q: 'How to finish homework faster', k: ['finish homework', 'homework fast', 'too much homework', 'homework done', 'do homework'],
    a: 'list all of it, start with the one due first, and do it in Pomodoros with your phone locked. homework drags because of switching, not because it\'s long. one task, one timer, done.', l: ['Open Timers', '/timers.html'] },
  { id: 'project', q: 'Tips for school projects', k: ['school project', 'project work', 'science project', 'project ideas', 'group project'],
    a: 'break it into parts with deadlines (research, draft, visuals, final). in group projects, assign one owner per part and set a check-in day. start early so the last night is for polishing, not panic.' },
  { id: 'speech', q: 'How to stop being nervous in presentations', k: ['nervous in presentations', 'presentations', 'presentation', 'public speaking', 'speech', 'stage fear', 'talk in front of class', 'debate'],
    a: "practise out loud 3 times (once in front of a mirror or a friend). know your first two lines by heart, they kill the nerves. look at a few friendly faces, and slow down, nervous people talk fast." },
  { id: 'olympiad', q: 'How to prepare for olympiads', k: ['olympiads', 'olympiad', 'competition exam', 'nso', 'imo', 'quiz competition'],
    a: "know your school syllabus solidly, then go beyond: solve past olympiad papers and puzzles. it's about reasoning more than memory, so practise thinking through tricky questions slowly." },
  { id: 'jee-neet', q: 'When should I start JEE or NEET prep?', k: ['jee', 'neet', 'iit', 'entrance exam', 'medical entrance', 'engineering entrance'],
    a: 'most people start seriously in class 11, but a strong class 9 and 10 base in maths and science is the real head start. focus on concepts, not just tricks, and protect your sleep. check official exam sites for current patterns.' },
  { id: 'typing', q: 'How to type faster', k: ['type faster', 'typing speed', 'typing practice', 'touch typing'],
    a: "learn touch typing (fingers on the home row: ASDF JKL;) and practise 10 minutes a day on any free typing site. accuracy first, speed comes on its own." },
  { id: 'coding-start', q: 'How do I start coding?', k: ['start coding', 'learn coding', 'learn programming', 'coding for beginners', 'which language first'],
    a: "start with Python, it reads almost like English. do small projects (a calculator, a quiz game) instead of only watching tutorials. 30 min a day beats 5 hours once a week. Maatram itself is built with HTML, CSS and JavaScript btw.", l: ['Maatram source code', 'https://github.com/MaatramReelsBlocking/maatram'] },
  { id: 'python-hello', q: 'Python hello world', k: ['python', 'hello world', 'print in python', 'first program'],
    a: 'here you go:\n```python\nprint("Hello, world!")\n```\nnext step: ask for a name with `name = input("Name? ")` then `print("Hi", name)`.' },
  { id: 'html', q: 'What is HTML?', k: ['html', 'what is html', 'make a website', 'web development', 'css', 'javascript'],
    a: 'HTML is the structure of a web page (headings, text, buttons). CSS makes it look good. JavaScript makes it do stuff. you can build a site with just those three, like Maatram.' },
  { id: 'what-ai', q: 'What is AI?', k: ['what is ai', 'artificial intelligence', 'machine learning', 'how does ai work', 'chatbot work'],
    a: 'AI = computer programs that learn patterns from tons of examples instead of following only hand-written rules. chatbots like me learned from loads of text, so we predict good answers. smart, but not always right.' },

  // ---------- Focus & screen time ----------
  { id: 'dopamine', q: 'Why are reels so addictive?', k: ['why reels addictive', 'dopamine', 'why cant i stop', 'addictive apps', 'algorithm'],
    a: "reels give tiny random rewards (a funny one, a boring one, a banger) and your brain gets hooked on the 'maybe the next one'. it's designed that way. that's why Maatram adds a cost and a pause before you open them." },
  { id: 'notifs', q: 'Should I turn off notifications?', k: ['notifications', 'turn off notifications', 'notification', 'pings', 'disturb'],
    a: 'yes, most of them. keep calls and maybe family chats, kill everything else. every ping pulls you out of focus and it takes a while to get back in. Do Not Disturb during study = cheat code.' },
  { id: 'grayscale', q: 'Does grayscale mode help?', k: ['grayscale mode', 'grayscale', 'greyscale', 'black and white screen', 'bedtime mode'],
    a: 'lowkey yes. colours make apps more tempting, grayscale makes them boring. on Android look for Bedtime mode or Grayscale in Digital Wellbeing settings.' },
  { id: 'wellbeing-app', q: 'Can my phone limit apps?', k: ['app timer', 'app limit', 'digital wellbeing', 'screen time iphone', 'limit apps', 'family link'],
    a: 'yep. Android has Digital Wellbeing (app timers, focus mode) and iPhone has Screen Time (app limits). pair those with Maatram Hard Lock for when you really need zero escape.', l: ['Arm Hard Lock', '/app-gate.html'] },
  { id: 'phone-away', q: 'Where should I keep my phone while studying?', k: ['keep phone away', 'phone in another room', 'phone while studying', 'phone near me'],
    a: 'another room if possible. even a phone lying face down on your desk pulls some of your attention. out of sight, out of mind is real.' },
  { id: 'music', q: 'Can I listen to music while studying?', k: ['music while studying', 'study music', 'lofi', 'songs while studying', 'music focus', 'white noise'],
    a: "lyric-free stuff (lofi, instrumental, white noise) is fine for many people. songs with lyrics mess with reading and memorising. also, pick a playlist BEFORE you start, not every 5 min." },
  { id: 'desk', q: 'Best study setup', k: ['study setup', 'study desk', 'study table', 'where to study', 'study place', 'study environment'],
    a: 'same spot every day, good light, chair with back support, water bottle, everything you need within reach. study on the bed and your brain goes "oh nap time".' },
  { id: 'gaming', q: "I can't stop gaming", k: ['cant stop playing', 'playing games', 'stop gaming', 'cant stop gaming', 'gaming', 'games', 'bgmi', 'free fire', 'video games', 'game addiction', 'minecraft'],
    a: "gaming's fine as a reward, not as the default. play AFTER your study blocks, set an alarm for when to stop, and keep the console or game off your phone's home screen. earn it, then enjoy it guilt-free." },
  { id: 'yt-study', q: 'YouTube for studying turns into scrolling', k: ['youtube study', 'youtube distract', 'youtube rabbit hole', 'watch lectures', 'shorts'],
    a: "classic trap. open the exact video from a link or playlist, not the home feed. full screen it. and lock Shorts and the rest with Hard Lock when you're not using YouTube for school." },
  { id: 'whatsapp', q: 'WhatsApp groups distract me', k: ['whatsapp group', 'group chats', 'chats distract', 'messages distract', 'texting'],
    a: 'mute the groups (forever is an option lol), check messages only in breaks, and tell friends you\'re studying till a certain time. they\'ll survive, promise.' },
  { id: 'fomo', q: 'I have FOMO if I log off', k: ['have fomo', 'log off', 'fomo', 'missing out', 'scared to miss', 'need to check'],
    a: "the feed will literally still be there in an hour, nothing important disappears. what you DO miss by scrolling is your own progress. check socials at set times instead of all the time." },
  { id: 'detox', q: 'How do I do a digital detox?', k: ['digital detox', 'social media break', 'delete instagram', 'quit social media', 'detox'],
    a: "you don't have to delete everything, that rarely lasts. start small: no phone first hour after waking, no phone in bed, and one Hard Lock a day. log your screen time to watch it drop.", l: ['Open Stats', '/stats.html'] },
  { id: 'screen-hours', q: 'How much screen time is too much?', k: ['too much screen time', 'how much screen time', 'screen time limit', 'hours on phone', 'normal screen time'],
    a: "there's no magic number, but ask: is it eating your sleep, homework or real-life time with people? if yes, it's too much. start by cutting 30 min a day and log it on Screen Stats.", l: ['Open Stats', '/stats.html'] },
  { id: 'night-phone', q: 'I use my phone in bed at night', k: ['phone at night', 'phone in bed', 'scroll at night', 'cant sleep phone', 'late night scrolling'],
    a: "the #1 sleep killer fr. charge your phone outside the room, use a cheap alarm clock, and stop screens 30 to 60 minutes before bed. you'll fall asleep faster, promise." },
  { id: 'morning', q: 'Good morning routine', k: ['good morning routine', 'morning routine', 'productive morning', 'start my day'],
    a: 'wake up, water, no phone for the first 30 min, quick stretch, breakfast, then glance at your plan for the day. starting with your own goals instead of other people\'s posts changes everything.' },
  { id: 'evening', q: 'Good evening routine', k: ['evening routine', 'after school routine', 'night routine', 'before bed routine'],
    a: 'snack + short rest after school, study blocks, dinner, light revision, then screens off and plan tomorrow in 2 minutes. sleep at the same time every night.' },
  { id: 'multitask', q: 'Can I multitask while studying?', k: ['multitask', 'multitasking', 'two things at once', 'study and watch'],
    a: "nope, multitasking is a myth. your brain just switches back and forth and loses time every switch. one task, one timer. faster AND better." },
  { id: 'flow', q: 'How do I get into the zone?', k: ['into the zone', 'get in the zone', 'flow state', 'in the zone', 'deep focus', 'lock in', 'locked in'],
    a: 'pick one clear task, remove distractions, and push through the first 10 to 15 min of "ugh". after that, focus usually kicks in. Deep Work blocks are made for this.', l: ['Open Timers', '/timers.html'] },
  { id: 'two-min', q: 'What is the 2-minute rule?', k: ['2 minute rule', 'two minute rule', 'small tasks', 'quick tasks'],
    a: "if something takes under 2 minutes (pack your bag, reply to the teacher), just do it now. and to start a big task, commit to only 2 minutes of it. you'll usually keep going." },
  { id: 'frog', q: 'What does eat the frog mean?', k: ['eat the frog mean', 'what does eat the frog', 'eat the frog', 'hardest task first', 'what to study first'],
    a: "do your hardest or most-dreaded task first, when your energy's highest. everything after it feels easy. the frog is probably maths, sorry." },
  { id: 'timeblock', q: 'What is time blocking?', k: ['time blocking', 'time block', 'block my time', 'schedule blocks'],
    a: 'give every task a fixed slot on your schedule, like 5:00 to 5:50 = chemistry. it stops the "what should I do now" loop and keeps your day honest.' },
  { id: 'todo', q: 'How to make a good to-do list', k: ['to do list', 'todo list', 'task list', 'checklist'],
    a: 'max 3 big things + a few small ones per day. write them as actions ("solve ex 4.2"), not vibes ("maths"). cross them off, it\'s weirdly satisfying.' },
  { id: 'priority', q: 'How to prioritize tasks', k: ['prioritize', 'prioritise', 'what to do first', 'eisenhower', 'urgent important'],
    a: 'sort tasks into: urgent + important (do now), important not urgent (schedule it), urgent not important (do fast), neither (skip). most studying lives in "important, not urgent", so schedule it before it becomes a crisis.' },
  { id: 'goals', q: 'How to set goals', k: ['set goals', 'goal setting', 'smart goals', 'my goals', 'targets'],
    a: 'make them SMART: specific, measurable, achievable, relevant, time-bound. "study more" ❌ vs "finish 2 Pomodoros of maths every school day this week" ✅' },
  { id: 'habits', q: 'How do I build a study habit?', k: ['build habit', 'study habit', 'consistency', 'be consistent', 'daily habit', 'streak'],
    a: "same time, same place, tiny start. attach it to something you already do (after evening tea → 1 Pomodoro). don't break the chain, streaks are motivating. Maatram points help you see the streak build.", l: ['Open Timers', '/timers.html'] },
  { id: 'reward', q: 'How should I reward myself?', k: ['reward myself', 'rewards', 'treat myself', 'motivation reward'],
    a: 'reward after the work, not before. finish 3 Pomodoros → 20 min of a show or a snack you love. and let Maatram points and the Leaderboard be part of the reward too.' },
  { id: 'accountability', q: 'I need someone to keep me accountable', k: ['accountability', 'study buddy', 'someone to check on me', 'keep me accountable'],
    a: "get a study buddy! jump in a Study Room together: shared timer, and everyone sees if someone opens a social app. peer pressure but make it productive.", l: ['Open Study Room', '/study-room.html'] },
  { id: 'weekend', q: 'How to use weekends well', k: ['weekends', 'use weekends', 'weekend', 'sunday', 'saturday', 'holidays', 'vacation study'],
    a: 'plan a few focused blocks in the morning and keep the rest free. use one block to revise the whole week. rest is part of the plan, burnout is not.' },
  { id: 'consistent-sleep', q: "I can't wake up early", k: ['cant wake up', 'wake up early', 'oversleep', 'snooze', 'alarm'],
    a: "it's usually a sleeping-late problem, not a waking-up problem. move bedtime 15 min earlier every few days, keep the alarm across the room, and get sunlight right after waking." },

  // ---------- Quick concepts (school) ----------
  { id: 'photosynthesis', q: 'What is photosynthesis?', k: ['explain photosynthesis', 'photosynthesis', 'plants make food', 'chlorophyll', 'how plants make food'],
    a: "green plants make their own food using sunlight, water and carbon dioxide, with chlorophyll catching the light.\n**6CO2 + 6H2O → C6H12O6 + 6O2** (with sunlight + chlorophyll)\nthey make glucose and release oxygen, the one we breathe 🌱" },
  { id: 'respiration', q: 'What is respiration?', k: ['respiration', 'aerobic', 'anaerobic', 'cellular respiration'],
    a: 'respiration = breaking down glucose to release energy. aerobic (with oxygen) gives carbon dioxide + water + lots of energy. anaerobic (no oxygen) gives less energy: lactic acid in our muscles, or alcohol + CO2 in yeast.' },
  { id: 'cell', q: 'Parts of a cell', k: ['cell organelles', 'parts of cell', 'mitochondria', 'nucleus', 'powerhouse of the cell', 'ribosome'],
    a: 'speedrun:\n- nucleus: control centre, has DNA\n- mitochondria: powerhouse, makes energy\n- ribosomes: make proteins\n- cell membrane: controls what goes in and out\n- plant cells also have a cell wall, chloroplasts and a big vacuole' },
  { id: 'newton', q: "Newton's laws of motion", k: ['newton', 'newtons laws', 'laws of motion', 'inertia', 'f ma', 'action reaction'],
    a: "1. **inertia**: things keep doing what they're doing unless a force acts\n2. **F = ma**: force = mass × acceleration\n3. **action-reaction**: every action has an equal and opposite reaction (rocket pushes gas down, gas pushes rocket up 🚀)" },
  { id: 'ohm', q: "Ohm's law", k: ['ohms law', 'ohm', 'v ir', 'resistance', 'voltage current'],
    a: '**V = I × R**: voltage = current × resistance (at constant temperature). so I = V ÷ R. example: 12 V across 4 Ω gives I = 12 ÷ 4 = 3 A.' },
  { id: 'speed', q: 'Speed, velocity and acceleration', k: ['speed', 'velocity', 'acceleration', 'distance time', 'displacement'],
    a: '**speed** = distance ÷ time (no direction). **velocity** = displacement ÷ time (has direction). **acceleration** = change in velocity ÷ time. e.g. 0 to 20 m/s in 4 s = 20 ÷ 4 = 5 m/s².' },
  { id: 'gravity', q: 'What is gravity?', k: ['gravity', 'gravitation', 'value of g', '9 8', 'weight and mass'],
    a: "gravity is the pull between any two masses. on Earth, g ≈ 9.8 m/s². mass = amount of stuff (kg, same everywhere). weight = mass × g (a force in newtons, changes on the Moon)." },
  { id: 'light', q: 'Reflection vs refraction', k: ['reflection', 'refraction', 'light bends', 'mirror', 'lens', 'snells law'],
    a: '**reflection**: light bounces off a surface (mirror), angle of incidence = angle of reflection. **refraction**: light bends when it goes from one medium to another (air → water), because its speed changes. that\'s why a straw looks bent in water.' },
  { id: 'atom', q: 'Structure of an atom', k: ['atom', 'structure of atom', 'proton', 'neutron', 'electron', 'atomic number'],
    a: 'nucleus in the centre with protons (+) and neutrons (no charge), electrons (−) moving in shells around it. atomic number = number of protons. mass number = protons + neutrons.' },
  { id: 'periodic', q: 'Tips for the periodic table', k: ['periodic table', 'elements', 'first 20 elements', 'groups and periods', 'valency'],
    a: 'rows = periods, columns = groups. first 20 trick: "Hi He Li Be B C N O F Ne, Na Mg Al Si P S Cl Ar, K Ca". say it like a rap 10 times and it sticks lol.' },
  { id: 'acids', q: 'Acids, bases and pH', k: ['what is ph', 'acid', 'acids', 'base', 'bases', 'ph', 'litmus', 'neutralisation', 'neutralization'],
    a: 'pH scale 0 to 14: below 7 = acid (lemon, vinegar), 7 = neutral (pure water), above 7 = base (soap, baking soda). acids turn blue litmus red; bases turn red litmus blue. acid + base → salt + water (neutralisation).' },
  { id: 'balance', q: 'How to balance chemical equations', k: ['balance equation', 'balancing equations', 'balance chemical', 'chemical equation'],
    a: 'count atoms of each element on both sides, then change only the numbers in FRONT (coefficients), never the small ones. e.g. H2 + O2 → H2O becomes **2H2 + O2 → 2H2O**. leave H and O for last if they appear in many compounds.' },
  { id: 'heart', q: 'How does the human heart work?', k: ['human heart', 'heart chambers', 'blood circulation', 'double circulation', 'arteries veins'],
    a: '4 chambers: 2 atria (top) receive blood, 2 ventricles (bottom) pump it. right side sends blood to the lungs to get oxygen, left side pumps oxygen-rich blood to the body. arteries carry blood away from the heart, veins bring it back.' },
  { id: 'dna', q: 'What is DNA?', k: ['what is dna', 'dna', 'genes', 'chromosomes', 'heredity', 'genetics'],
    a: "DNA is the instruction manual in your cells, shaped like a twisted ladder (double helix). genes are sections of DNA that code for traits. chromosomes are DNA packed up tight. humans have 23 pairs." },
  { id: 'water-cycle', q: 'Explain the water cycle', k: ['water cycle', 'evaporation', 'condensation', 'precipitation', 'rain cycle'],
    a: 'sun heats water → **evaporation** (water vapour rises) → **condensation** (vapour cools into clouds) → **precipitation** (rain, snow) → water collects in rivers, seas and ground → repeat ♻️' },
  { id: 'food-chain', q: 'What is a food chain?', k: ['food chain', 'food web', 'producers consumers', 'ecosystem', 'decomposers'],
    a: 'who eats who: grass (producer) → grasshopper (primary consumer) → frog → snake → eagle. decomposers like fungi and bacteria break down dead stuff and return nutrients to the soil. only about 10% of energy passes to each next level.' },
  { id: 'pythagoras', q: 'Pythagoras theorem', k: ['pythagoras', 'pythagorean', 'hypotenuse', 'right triangle', 'a2 b2 c2'],
    a: "in a right-angled triangle: **a² + b² = c²**, where c is the hypotenuse (longest side). e.g. sides 3 and 4 → c² = 9 + 16 = 25, so c = 5." },
  { id: 'quadratic', q: 'Quadratic formula', k: ['quadratic formula', 'quadratic equation', 'discriminant', 'roots of equation', 'ax2 bx c'],
    a: 'for ax² + bx + c = 0: **x = (−b ± √(b² − 4ac)) ÷ 2a**. the discriminant D = b² − 4ac: D > 0 two real roots, D = 0 one repeated root, D < 0 no real roots.' },
  { id: 'trig', q: 'Trigonometry ratios', k: ['trigonometry', 'sin cos tan', 'sohcahtoa', 'trig ratios', 'trigonometric'],
    a: '**SOH CAH TOA**: sin = opposite ÷ hypotenuse, cos = adjacent ÷ hypotenuse, tan = opposite ÷ adjacent. key values: sin 30° = 1/2, cos 60° = 1/2, tan 45° = 1, sin 90° = 1.' },
  { id: 'circle', q: 'Area and circumference of a circle', k: ['area of circle', 'circumference', 'circle formula', 'pi r square', 'radius'],
    a: '**area = πr²**, **circumference = 2πr** (π ≈ 3.14 or 22/7). e.g. r = 7 cm → area = 22/7 × 49 = 154 cm², circumference = 2 × 22/7 × 7 = 44 cm.' },
  { id: 'hcf', q: 'HCF and LCM', k: ['hcf', 'lcm', 'gcd', 'highest common factor', 'lowest common multiple'],
    a: 'HCF = biggest number that divides both. LCM = smallest number both divide into. use prime factors: 12 = 2²×3, 18 = 2×3². HCF = 2×3 = 6, LCM = 2²×3² = 36. bonus: HCF × LCM = product of the two numbers (6 × 36 = 12 × 18).' },
  { id: 'percent', q: 'How to calculate percentage', k: ['percentage', 'percent', 'how to find percentage', 'marks percentage'],
    a: 'percentage = (part ÷ total) × 100. e.g. 45 out of 60 = 45 ÷ 60 × 100 = 75%. to find 20% of 250: 0.2 × 250 = 50.' },
  { id: 'interest', q: 'Simple and compound interest', k: ['simple interest', 'compound interest', 'si formula', 'ci formula', 'interest'],
    a: '**simple interest** = P × R × T ÷ 100. **compound amount** = P(1 + R/100)ⁿ, then CI = amount − P. e.g. ₹1000 at 10% for 2 years: SI = ₹200; compound amount = 1000 × 1.21 = ₹1210, so CI = ₹210.' },
  { id: 'parts-speech', q: 'Parts of speech', k: ['parts of speech', 'noun', 'verb', 'adjective', 'adverb', 'pronoun', 'preposition'],
    a: '8 of them: noun (thing), pronoun (he, it), verb (action), adjective (describes noun), adverb (describes verb: quickly), preposition (on, under), conjunction (and, but), interjection (wow!).' },
  { id: 'tenses', q: 'Explain tenses', k: ['tenses', 'tense', 'past tense', 'present perfect', 'future tense', 'continuous tense'],
    a: 'past / present / future, each in 4 forms. present examples: simple (I study), continuous (I am studying), perfect (I have studied), perfect continuous (I have been studying since 5). swap the helper verbs to get past (had, was) and future (will).' },
  { id: 'voice', q: 'Active vs passive voice', k: ['active voice', 'passive voice', 'active passive', 'change voice'],
    a: 'active: the doer comes first. "Ravi wrote the letter." passive: the thing done comes first. "The letter was written by Ravi." formula: object + be-verb + past participle + by + doer.' },
  { id: 'french-rev', q: 'French Revolution quick notes', k: ['french revolution', '1789', 'bastille', 'liberty equality fraternity'],
    a: 'started in 1789 with the storming of the Bastille. causes: debt, unfair taxes on the Third Estate, food shortages, Enlightenment ideas. key ideas: liberty, equality, fraternity. it ended the monarchy and inspired movements everywhere.' },
  { id: 'india-indep', q: 'Indian independence key dates', k: ['indian independence', 'independence', 'independence day', '1947', 'republic day', '1950', 'indian constitution', 'freedom struggle'],
    a: 'India got independence on 15 August 1947. the Constitution came into effect on 26 January 1950 (Republic Day). Dr B. R. Ambedkar chaired the drafting committee.' },
  { id: 'democracy', q: 'What is democracy?', k: ['democracy', 'democratic', 'election', 'government types', 'parliament'],
    a: 'democracy = the people choose their rulers through free and fair elections, with rights protected by law. India is the world\'s largest democracy, with a Parliament (Lok Sabha + Rajya Sabha) that makes laws.' },
  { id: 'binary', q: 'What is binary?', k: ['binary', 'binary numbers', 'base 2', 'bits', 'convert to binary'],
    a: 'binary uses only 0 and 1 (base 2), which is how computers store everything. place values: 8 4 2 1. so 1011 = 8 + 0 + 2 + 1 = 11. one binary digit = a bit, 8 bits = a byte.' },
  { id: 'climate', q: 'What is climate change?', k: ['climate change', 'global warming', 'greenhouse effect', 'greenhouse gases', 'pollution'],
    a: 'burning coal, oil and gas adds greenhouse gases (like CO2) that trap heat, so the planet warms up. results: hotter summers, melting ice, rising seas, wilder weather. saving energy, planting trees and less waste all help.' },

  // ---------- Careers ----------
  { id: 'stream', q: 'Which stream after 10th?', k: ['stream after 10th', 'science or commerce', 'which stream', 'after class 10', 'choose stream', 'pcm pcb'],
    a: "pick by what you actually enjoy + what careers you're curious about, not what your friends pick. science (PCM: engineering/tech, PCB: medicine/biology), commerce (business, CA, finance), humanities (law, design, psychology, civil services and more). talk to a counsellor and people already in that field." },
  { id: 'career', q: 'I don\'t know what career I want', k: ['which career', 'career options', 'dont know career', 'future job', 'what should i become'],
    a: "totally normal at your age. try stuff: online courses, clubs, small projects, talking to people in different jobs. notice what you'd do even without marks. the AI version of me can explore specific careers with you, just ask." },
  { id: 'commerce', q: 'Careers in commerce', k: ['commerce careers', 'chartered accountant', 'ca', 'business career', 'finance career', 'bba'],
    a: 'popular routes: CA (chartered accountant), CS, CMA, BBA/BCom then MBA, banking and finance, economics, entrepreneurship. maths with commerce opens extra doors like economics and data careers.' },
  { id: 'humanities', q: 'Careers in humanities', k: ['humanities careers', 'arts stream', 'psychology', 'law career', 'design career', 'civil services'],
    a: 'humanities opens law, psychology, journalism, design, civil services, teaching, economics, international relations and more. it\'s not the "easy stream", it\'s the reading-and-thinking stream.' },
  { id: 'tech-career', q: 'How to get into tech', k: ['get into tech', 'tech', 'tech career', 'software engineer', 'computer science', 'become developer', 'it job'],
    a: 'learn to code early (Python or JavaScript), build small real projects, put them on GitHub, and keep maths strong. a CS degree helps, but your projects show what you can actually do.' },

  // ---------- More Maatram ----------
  { id: 'hardlock-app', q: 'What is the Maatram Hard Lock app?', k: ['maatram hard lock app', 'hard lock app', 'lock app', 'hard lock android app', 'hard lock app', 'hardlock apk', 'maatram hard lock android', 'lighter app', 'com maatram hardlock', 'clear all'],
    a: 'Maatram Hard Lock is the lighter Android app: Hard Lock only. it locks just the apps you pick and keeps running even when you hit "Clear all". version 2.4 alpha, 2.82 MB, Android 8.0 and above. it sorts apps to lock by your screen time, and grows a sakura while you lock: any finished lock gives a blooming tree, a 90-minute lock gives a full tree. there is a home-screen widget too. you can install it next to the full app, they don\'t clash.', l: ['Download', '/download.html'] },
  { id: 'full-app', q: 'What is in the full Maatram app?', k: ['full app', 'maatram full app', 'version 1 1', 'com maatram app', 'which apk'],
    a: 'the full Maatram app has every feature from the website plus native app blocking. version 1.1, 2.90 MB, Android 5.1 and above. it\'s stable but not getting updates; the Hard Lock app is the one being kept up to date.', l: ['Download', '/download.html'] },
  { id: 'iphone', q: 'Does Maatram work on iPhone?', k: ['work on iphone', 'iphone', 'ios app', 'apple', 'ipad', 'mac'],
    a: "no iPhone app yet, sorry 😔 but the whole website works in Safari, so timers, Study Rooms, Stats and the rest still work. just no native app blocking on iPhone." },
  { id: 'opensource', q: 'Is Maatram open source?', k: ['open source', 'source code', 'mit license', 'contribute', 'pull request', 'github repo'],
    a: "yep, open source under the MIT licence. the code is on GitHub (MaatramReelsBlocking/maatram) and changes run through automated checks before they ship. contributions and issues are welcome.", l: ['GitHub', 'https://github.com/MaatramReelsBlocking/maatram'] },
  { id: 'cheat-points', q: 'Can I hack or farm points?', k: ['hack points', 'cheat points', 'farm points', 'free points', 'points glitch', 'exploit'],
    a: "lol nice try 😂 points are meant to show real focus. scripts, bug exploits or impersonating someone can get your points reset (it's in the terms). earn them the honest way, it feels better anyway.", l: ['Terms', '/terms.html'] },
  { id: 'room-privacy', q: 'Is Study Room chat private?', k: ['room chat private', 'study room privacy', 'chat safe', 'who can see chat', 'room code safe'],
    a: "not fully. Study Rooms sync through a public relay and the room code is the channel, so anyone with the code can see that traffic. messages aren't stored though. never share personal info (phone, address) in room chat.", l: ['Privacy policy', '/privacy.html'] },
  { id: 'analytics', q: 'Does Maatram track me?', k: ['track me', 'does maatram track', 'analytics', 'clarity', 'tracking', 'cookies', 'does it track'],
    a: 'the site uses Microsoft Clarity, Vercel Web Analytics and Vercel Speed Insights to see how pages are used and how fast they load. your Stats entries stay in your browser. full details are on the privacy page.', l: ['Privacy policy', '/privacy.html'] },
  { id: 'delete-data', q: 'How do I delete my account or data?', k: ['delete account', 'delete my data', 'remove account', 'erase data', 'clear my data'],
    a: "Stats, Wellness and other on-device data clear when you clear this site's data in your browser. for your signed-in account, check the privacy page or email the team at maatram97@gmail.com.", l: ['Privacy policy', '/privacy.html'], mail: true },
  { id: 'friction', q: 'What happens when I open a social app on App Gate?', k: ['open a social app on app gate', 'social app on app gate', 'friction', 'pause before app', 'worth it', 'reopen app', 'open instagram on app gate'],
    a: "you don't just get blocked, you pay: opening a social app costs 10 points plus a short pause that grows the more you reopen it, and afterwards an honest \"was it worth it?\" check-in. annoying on purpose 😌", l: ['Open App Gate', '/app-gate.html'] },
  { id: 'class-code', q: 'Where are class codes and roles?', k: ['class code', 'roles', 'teacher', 'parent', 'student role', 'role picker'],
    a: 'the role picker and class codes were removed. now every tool just opens without an account, and signing in with Google saves your points.', l: ['Updates', '/blog.html'] },
  { id: 'updates', q: "What's new on Maatram?", k: ['whats new', 'updates', 'changelog', 'new features', 'latest update', 'blog'],
    a: 'the Updates page has the changelog in the team\'s own words, recent stuff like Wellness, the Chrome extension and simpler sign-in.', l: ['See updates', '/blog.html'] },
  { id: 'weekly-bonus', q: 'How does the weekly bonus work?', k: ['weekly bonus', 'under average', 'bonus points', '50 points'],
    a: 'log your screen time on Stats. if your week comes in under your own weekly average, you get +50 pts automatically. beat your past self = get paid 😎', l: ['Open Stats', '/stats.html'] },
  { id: 'max-points', q: 'Most points I can earn from one Hard Lock', k: ['most points', 'earn from one hard lock', 'max points', 'most points', '180 points', 'best way to earn', 'earn fast'],
    a: 'Hard Lock pays +10 for every 5 minutes, so a full 90 minute lock = +180 pts. a Deep Work session is +100. stack them: Deep Work while a Hard Lock is running 👀', l: ['Arm Hard Lock', '/app-gate.html'] },
  { id: 'shortcuts', q: 'Timer keyboard shortcuts', k: ['keyboard shortcut', 'shortcuts', 'space bar', 'press r', 'hotkeys'],
    a: 'on the Timers page: Space starts or pauses, R resets. speedrun mode.', l: ['Open Timers', '/timers.html'] },
  { id: 'post-sport', q: 'How do I post a sports event?', k: ['post a sports event', 'post sports', 'post event', 'list event', 'add tournament', 'organise event', 'sports listing'],
    a: 'sign in, open Sports Corner and add your event (title, sport, city, date, venue, organiser, registration link). signed-in users can see listings, and registration always goes to the organiser\'s own page.', l: ['Open Sports Corner', '/sports.html'] },
  { id: 'wellness-medical', q: 'Is Wellness medical advice?', k: ['medical advice', 'doctor', 'dietician', 'allergy', 'nutritionist'],
    a: "no, Wellness is general guidance for everyday habits, not medical or nutrition advice. for allergies, health conditions or special diets, check with a doctor or parent first." },
  { id: 'sakura', q: 'What is the sakura on App Gate?', k: ['sakura', 'tree', 'plant', 'garden', 'my garden', 'grow a tree', 'leaves dropped', 'leaf dropped', 'widget', 'home screen widget'],
    a: "your sakura 🌸 start a Hard Lock and a seed gets planted. it grows into a blooming tree while you stay locked, with a sky that follows the real time of day. every time you try a locked app, the tree drops a leaf. finished locks get planted in My garden with your streak and a 4-week grid. the Hard Lock Android app (v2.0) has the same tree plus a home-screen widget.", l: ['Open App Gate', '/app-gate.html'] },
  { id: 'offline', q: 'Does Focuz work offline?', k: ['focuz offline', 'work offline', 'offline', 'no internet', 'without internet', 'ai busy', 'not answering'],
    a: "when the AI can't be reached I switch to my built-in brain, which knows Maatram and a bunch of study topics. for homework in any subject, check your internet and ask again in a moment." }
]);
